// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildMessage.proto

#include "BuildMessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ubavs {
PROTOBUF_CONSTEXPR BuildMessage::BuildMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.environment_)*/{}
  , /*decltype(_impl_.commandline_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.currentdirectory_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct BuildMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildMessageDefaultTypeInternal() {}
  union {
    BuildMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildMessageDefaultTypeInternal _BuildMessage_default_instance_;
}  // namespace ubavs
static ::_pb::Metadata file_level_metadata_BuildMessage_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_BuildMessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_BuildMessage_2eproto = nullptr;

const uint32_t TableStruct_BuildMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::ubavs::BuildMessage, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::ubavs::BuildMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ubavs::BuildMessage, _impl_.commandline_),
  PROTOBUF_FIELD_OFFSET(::ubavs::BuildMessage, _impl_.currentdirectory_),
  PROTOBUF_FIELD_OFFSET(::ubavs::BuildMessage, _impl_.environment_),
  0,
  1,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::ubavs::BuildMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ubavs::_BuildMessage_default_instance_._instance,
};

const char descriptor_table_protodef_BuildMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022BuildMessage.proto\022\005ubavs\"\201\001\n\014BuildMes"
  "sage\022\030\n\013commandLine\030\001 \001(\tH\000\210\001\001\022\035\n\020curren"
  "tDirectory\030\002 \001(\tH\001\210\001\001\022\023\n\013environment\030\003 \003"
  "(\tB\016\n\014_commandLineB\023\n\021_currentDirectoryb"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_BuildMessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_BuildMessage_2eproto = {
    false, false, 167, descriptor_table_protodef_BuildMessage_2eproto,
    "BuildMessage.proto",
    &descriptor_table_BuildMessage_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_BuildMessage_2eproto::offsets,
    file_level_metadata_BuildMessage_2eproto, file_level_enum_descriptors_BuildMessage_2eproto,
    file_level_service_descriptors_BuildMessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_BuildMessage_2eproto_getter() {
  return &descriptor_table_BuildMessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_BuildMessage_2eproto(&descriptor_table_BuildMessage_2eproto);
namespace ubavs {

// ===================================================================

class BuildMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<BuildMessage>()._impl_._has_bits_);
  static void set_has_commandline(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_currentdirectory(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

BuildMessage::BuildMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ubavs.BuildMessage)
}
BuildMessage::BuildMessage(const BuildMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BuildMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.environment_){from._impl_.environment_}
    , decltype(_impl_.commandline_){}
    , decltype(_impl_.currentdirectory_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.commandline_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.commandline_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_commandline()) {
    _this->_impl_.commandline_.Set(from._internal_commandline(), 
      _this->GetArenaForAllocation());
  }
  _impl_.currentdirectory_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.currentdirectory_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_currentdirectory()) {
    _this->_impl_.currentdirectory_.Set(from._internal_currentdirectory(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ubavs.BuildMessage)
}

inline void BuildMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.environment_){arena}
    , decltype(_impl_.commandline_){}
    , decltype(_impl_.currentdirectory_){}
  };
  _impl_.commandline_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.commandline_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.currentdirectory_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.currentdirectory_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BuildMessage::~BuildMessage() {
  // @@protoc_insertion_point(destructor:ubavs.BuildMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BuildMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.environment_.~RepeatedPtrField();
  _impl_.commandline_.Destroy();
  _impl_.currentdirectory_.Destroy();
}

void BuildMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BuildMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ubavs.BuildMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.environment_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.commandline_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.currentdirectory_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BuildMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string commandLine = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_commandline();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ubavs.BuildMessage.commandLine"));
        } else
          goto handle_unusual;
        continue;
      // optional string currentDirectory = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_currentdirectory();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ubavs.BuildMessage.currentDirectory"));
        } else
          goto handle_unusual;
        continue;
      // repeated string environment = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_environment();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ubavs.BuildMessage.environment"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BuildMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ubavs.BuildMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional string commandLine = 1;
  if (_internal_has_commandline()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_commandline().data(), static_cast<int>(this->_internal_commandline().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ubavs.BuildMessage.commandLine");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_commandline(), target);
  }

  // optional string currentDirectory = 2;
  if (_internal_has_currentdirectory()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_currentdirectory().data(), static_cast<int>(this->_internal_currentdirectory().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ubavs.BuildMessage.currentDirectory");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_currentdirectory(), target);
  }

  // repeated string environment = 3;
  for (int i = 0, n = this->_internal_environment_size(); i < n; i++) {
    const auto& s = this->_internal_environment(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ubavs.BuildMessage.environment");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ubavs.BuildMessage)
  return target;
}

size_t BuildMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ubavs.BuildMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string environment = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.environment_.size());
  for (int i = 0, n = _impl_.environment_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.environment_.Get(i));
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string commandLine = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_commandline());
    }

    // optional string currentDirectory = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_currentdirectory());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BuildMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BuildMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BuildMessage::GetClassData() const { return &_class_data_; }


void BuildMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BuildMessage*>(&to_msg);
  auto& from = static_cast<const BuildMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ubavs.BuildMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.environment_.MergeFrom(from._impl_.environment_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_commandline(from._internal_commandline());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_currentdirectory(from._internal_currentdirectory());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BuildMessage::CopyFrom(const BuildMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ubavs.BuildMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BuildMessage::IsInitialized() const {
  return true;
}

void BuildMessage::InternalSwap(BuildMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.environment_.InternalSwap(&other->_impl_.environment_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.commandline_, lhs_arena,
      &other->_impl_.commandline_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.currentdirectory_, lhs_arena,
      &other->_impl_.currentdirectory_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata BuildMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BuildMessage_2eproto_getter, &descriptor_table_BuildMessage_2eproto_once,
      file_level_metadata_BuildMessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ubavs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ubavs::BuildMessage*
Arena::CreateMaybeMessage< ::ubavs::BuildMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ubavs::BuildMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
